targets = main
main: "3 - Longest Substring Without Repeating Characters.cpp"
	g++ "3 - Longest Substring Without Repeating Characters.cpp" -o sol
#g++ "3 - Longest Substring Without Repeating Characters.cpp" -o sol
